name: drupal
type: 'php:8.0'
dependencies:
    php:
        composer/composer: ^2
runtime:
    extensions:
        - redis
        - sodium
        - apcu
        - blackfire
relationships:
    rediscache: 'cache:redis'
    first: 'db:first'
    second: 'db:second'
    main: 'db:main'
disk: 2048
mounts:
    /web/files:
        source: local
        source_path: files
    /tmp:
        source: local
        source_path: tmp
    /private:
        source: local
        source_path: private
    /.drush:
        source: local
        source_path: drush
    /drush-backups:
        source: local
        source_path: drush-backups
    /.console:
        source: local
        source_path: console
build:
    flavor: composer
hooks:
    build: |
        set -e
    deploy: |
        set -e
        php ./drush/platformsh_generate_drush_yml.php
        cd web
        drush -y cache-rebuild
        drush -y updatedb
        drush -y config-import
web:
    locations:
        /:
            root: web
            expires: 5m
            passthru: /index.php
            allow: false
            rules:
                '\.(jpe?g|png|gif|svgz?|css|js|map|ico|bmp|eot|woff2?|otf|ttf)$':
                    allow: true
                ^/robots\.txt$:
                    allow: true
                ^/sitemap\.xml$:
                    allow: true
                ^/sites/sites\.php$:
                    scripts: false
                '^/sites/[^/]+/settings.*?\.php$':
                    scripts: false
        /files:
            allow: true
            expires: 5m
            passthru: /index.php
            root: web/files
            scripts: false
            rules:
                ^/files/(css|js):
                    expires: 2w
crons:
    drupal:
        spec: '*/19 * * * *'
        cmd: 'cd web ; drush core-cron'
source:
    operations:
        auto-update:
            command: |
                curl -fsS https://raw.githubusercontent.com/platformsh/source-operations/main/setup.sh | { bash /dev/fd/3 sop-autoupdate; } 3<&0
