db:
    type: 'mariadb:10.4'
    disk: 2048
    configuration:
        schemas:
            - firstdb
            - seconddb
            - main
        endpoints:
            first:
                default_schema: firstdb
                privileges:
                    firstdb: admin
            second:
                default_schema: seconddb
                privileges:
                    seconddb: admin
            main:
                default_schema: main
                privileges:
                    main: admin
cache:
    type: 'redis:6.0'
